/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push1_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push1_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push1_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push1_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push1_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push1_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push2_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push2_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push2_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push2_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push2_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push3_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push3_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push3_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push3_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push3_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push3_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push4_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push4_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push4_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push4_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push4_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push4_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push5_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push5_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push5_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push5_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push5_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push5_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_push6_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_push6_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_push6_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_push6_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_push6_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_push6_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD1 (number 74), J2[12]/D3[3]/D13/LEDRGB_BLUE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
